# Generated by Django 2.2 on 2020-01-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='identifiers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.IndustryIdentifiers'),
        ),
    ]
