# Generated by Django 2.2 on 2020-01-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200121_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='industryidentifiers',
            options={'verbose_name': 'identifier', 'verbose_name_plural': 'indetifiers'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='book',
            name='identifiers',
            field=models.ManyToManyField(to='books.IndustryIdentifiers'),
        ),
    ]
