# Generated by Django 2.2 on 2020-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200121_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='identifiers',
            field=models.ManyToManyField(to='books.IndustryIdentifiers'),
        ),
    ]
