# Generated by Django 2.2 on 2020-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200121_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='identifiers',
            field=models.ManyToManyField(to='books.IndustryIdentifiers'),
        ),
    ]
